api:
  image: kuberlab/aptekar:latest
  serviceType: ClusterIP
  imagePullPolicy: Always
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
  postgres:
    host: "localhost"
    port: "5432"
    user: "postgres"
    password: ""
  predicted:
    fake: false
    amiraHost: ""
ui:
  image: kuberlab/aptekar-ui:latest
  serviceType: ClusterIP
  imagePullPolicy: Always
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
