API:
  Image:
    kuberlab.io/image:
      Name: kuberlab/aptekar
      Tag: latest
      CandidateTag: '>= 1.0.0'
  serviceType: ClusterIP
  imagePullPolicy: Always
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
  postgres:
    host: "localhost"
    port: "5432"
    user: "postgres"
    password: ""
  predicted:
    fake: false
    amiraHost: ""
    amiraPort: 9000
    lstmHost: ""
    lstmPort: 9000
UI:
  Image:
    kuberlab.io/image:
      Name: kuberlab/aptekar-ui
      Tag: latest
      CandidateTag: '>= 1.0.0'
  serviceType: ClusterIP
  imagePullPolicy: Always
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
