API:
  Image:
    kuberlab.io/image:
      Name: kuberlab/aptekar
      Tag: latest
      CandidateTag: '>= 1.0.0'
  serviceType: NodePort
  nodePort: 30700
  imagePullPolicy: Always
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
  postgres:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: ""
  clickhouse:
    host: "localhost"
    port: 9000
  predicted:
    fake: false
    arimaHost: ""
    arimaPort: 9000
    lstmHost: ""
    lstmPort: 9000
    fireHost: ""
    firePort: 9000
UI:
  Image:
    kuberlab.io/image:
      Name: kuberlab/aptekar-ui
      Tag: latest
      CandidateTag: '>= 1.0.0'
  serviceType: NodePort
  nodePort: 30701
  imagePullPolicy: Always
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
