API:
  Image:
    Name: kuberlab/aptekar
    Tag: latest
  serviceType: ClusterIP
  imagePullPolicy: Always
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
  postgres:
    host: "localhost"
    port: "5432"
    user: "postgres"
    password: ""
  predicted:
    fake: false
    amiraHost: ""
ui:
  Image:
    Name: kuberlab/aptekar-ui
    Tag: latest
  serviceType: ClusterIP
  imagePullPolicy: Always
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
