apiVersion: v1
kind: Service
metadata:
  name: aptekar-api
  labels:
    app: aptekar
    component: aptekar-api
spec:
  type: {{ .Values.api.serviceType }}
  ports:
  - name: http
    port: 8082
    targetPort: http
    protocol: TCP
  selector:
    app: aptekar
    component: aptekar-api
