apiVersion: v1
kind: Service
metadata:
  name: aptekar-api
  labels:
    app: aptekar
    component: aptekar-api
spec:
  type: {{ .Values.API.serviceType }}
  ports:
  - name: http
    port: 8082
    targetPort: http
    protocol: TCP
    {{- if eq .Values.API.serviceType "NodePort" }}
    {{- if .Values.API.nodePort }}
    nodePort: {{ .Values.API.nodePort }}
    {{- end }}
    {{- end }}
  selector:
    app: aptekar
    component: aptekar-api
