apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aptekar-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aptekar
        component: aptekar-api
    spec:
      containers:
      - name: aptekar-api
        image: {{ .Values.api.image }}
        readinessProbe:
          httpGet:
            path: /probe
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        imagePullPolicy: {{ default "" .Values.api.imagePullPolicy | quote }}
        env:
        - name: PG_HOST
          value: {{ default "localhost" .Values.api.postgresHost | quote }}
        - name: PG_PORT
          value: {{ default "5432" .Values.api.postgresPort | quote }}
        - name: PG_USER
          value: {{ default "postgres" .Values.api.postgresUser | quote }}
        - name: PG_PWD
          value: {{ default "" .Values.api.postgresPassword | quote }}
        ports:
        - name: http
          containerPort: 8082
        resources:
{{ toYaml .Values.api.resources | indent 10 }}
