apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aptekar-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aptekar
        component: aptekar-api
    spec:
      containers:
      - name: aptekar-api
        image: {{ .Values.API.Image.Name }}:{{ .Values.API.Image.Tag }}
        readinessProbe:
          httpGet:
            path: /probe
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        imagePullPolicy: {{ default "" .Values.API.imagePullPolicy | quote }}
        env:
        - name: PG_HOST
          value: {{ default "localhost" .Values.API.postgres.host | quote }}
        - name: PG_PORT
          value: {{ default "5432" .Values.API.postgres.port | quote }}
        - name: PG_USER
          value: {{ default "postgres" .Values.API.postgres.user | quote }}
        - name: PG_PWD
          value: {{ default "" .Values.API.postgres.password | quote }}
        - name: FAKE_PREDICTED
          value: {{ default "false" .Values.API.predicted.fake | quote }}
        - name: AMIRA_HOST
          value: {{ default "" .Values.API.predicted.amiraHost | quote }}
        - name: AMIRA_PORT
          value: {{ default "" .Values.API.predicted.amiraPort | quote }}
        - name: LSTM_HOST
          value: {{ default "" .Values.API.predicted.lstmHost | quote }}
        - name: LSTM_PORT
          value: {{ default "" .Values.API.predicted.lstmPort | quote }}
        - name: FIRE_HOST
          value: {{ default "" .Values.API.predicted.fireHost | quote }}
        - name: FIRE_PORT
          value: {{ default "" .Values.API.predicted.firePort | quote }}
        ports:
        - name: http
          containerPort: 8082
        resources:
{{ toYaml .Values.API.resources | indent 10 }}
