apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aptekar-ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aptekar
        component: aptekar-ui
    spec:
      containers:
      - name: aptekar-ui
        image: {{ .Values.UI.Image.Name }}:{{ .Values.UI.Image.Tag }}
        imagePullPolicy: {{ default "" .Values.api.imagePullPolicy | quote }}
        ports:
        - name: http
          containerPort: 80
        resources:
{{ toYaml .Values.UI.resources | indent 10 }}
