apiVersion: v1
kind: Service
metadata:
  name: aptekar-ui
  labels:
    app: aptekar
    component: aptekar-ui
spec:
  type: {{ .Values.UI.serviceType }}
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    {{- if eq .Values.UI.serviceType "NodePort" }}
    {{- if .Values.UI.nodePort }}
    nodePort: {{ .Values.UI.nodePort }}
    {{- end }}
    {{- end }}
  selector:
    app: aptekar
    component: aptekar-ui
